import React, { useState } from 'react';
import { Upload, Download, Settings, Terminal, Image, Film, Code, Check, AlertCircle, Copy, Play, Zap } from 'lucide-react';

export default function TerminalBGSetup() {
  const [activeTab, setActiveTab] = useState('select');
  const [selectedTerminal, setSelectedTerminal] = useState('');
  const [selectedMethod, setSelectedMethod] = useState('');
  const [selectedFile, setSelectedFile] = useState(null);
  const [opacity, setOpacity] = useState(0.85);
  const [generatedConfig, setGeneratedConfig] = useState('');
  const [copied, setCopied] = useState(false);

  const terminals = [
    { id: 'kitty', name: 'Kitty', supports: ['image', 'gif', 'video'], difficulty: 'Easy', popular: true },
    { id: 'alacritty', name: 'Alacritty', supports: ['image'], difficulty: 'Medium', popular: true },
    { id: 'konsole', name: 'Konsole', supports: ['image'], difficulty: 'Easy', popular: false },
    { id: 'terminator', name: 'Terminator', supports: ['image'], difficulty: 'Easy', popular: false },
    { id: 'coolretro', name: 'Cool Retro Term', supports: ['image', 'gif', 'video', 'html'], difficulty: 'Easy', popular: true },
    { id: 'urxvt', name: 'URxvt', supports: ['image'], difficulty: 'Hard', popular: false },
  ];

  const methods = [
    { id: 'image', name: 'Static Image', icon: Image, desc: 'PNG/JPG background', compatible: 'all' },
    { id: 'gif', name: 'Animated GIF', icon: Film, desc: 'Looping animation', compatible: 'kitty, coolretro' },
    { id: 'video', name: 'Video Background', icon: Play, desc: 'MP4/WebM video', compatible: 'kitty, coolretro' },
    { id: 'html', name: 'Live HTML', icon: Code, desc: 'Interactive animations', compatible: 'coolretro' },
  ];

  const presets = [
    {
      id: 'skeleton-vhs',
      name: '💀 Skeleton VHS',
      description: 'Retro glitch aesthetic with chromatic aberration',
      opacity: 0.85,
      effect: 'VHS Glitch',
      color: 'Monochrome',
      gradient: 'from-gray-900 to-gray-700',
      terminal: 'coolretro',
      method: 'html'
    },
    {
      id: 'matrix-rain',
      name: '🟢 Matrix Rain',
      description: 'Classic falling code animation',
      opacity: 0.75,
      effect: 'Code Rain',
      color: 'Green Phosphor',
      gradient: 'from-green-900 to-emerald-700',
      terminal: 'coolretro',
      method: 'html'
    },
    {
      id: 'cyberpunk-city',
      name: '🌃 Cyberpunk City',
      description: 'Neon cityscape with rain effects',
      opacity: 0.80,
      effect: 'Rain Overlay',
      color: 'Neon Pink/Blue',
      gradient: 'from-pink-900 to-purple-700',
      terminal: 'kitty',
      method: 'video'
    },
    {
      id: 'minimal-nord',
      name: '❄️ Minimal Nord',
      description: 'Clean Nordic color palette',
      opacity: 0.90,
      effect: 'None',
      color: 'Nord Theme',
      gradient: 'from-blue-900 to-slate-700',
      terminal: 'alacritty',
      method: 'image'
    }
  ];

  const generateConfig = () => {
    if (!selectedTerminal || !selectedMethod) return;

    let config = '';
    const imagePath = selectedFile ? selectedFile.name : '~/Pictures/terminal_bg.png';

    switch (selectedTerminal) {
      case 'kitty':
        config = `# Kitty Configuration (~/.config/kitty/kitty.conf)
# Generated by Terminal BG Setup Tool

background_image ${imagePath}
background_image_layout scaled
background_opacity ${opacity}
background_tint 0.85

# Optional: Additional settings
cursor_blink_interval 0
window_padding_width 10
font_size 12.0

# Reload Kitty after saving:
# Press Ctrl+Shift+F5 or restart Kitty`;
        break;

      case 'alacritty':
        config = `# Alacritty Configuration (~/.config/alacritty/alacritty.yml)
# Generated by Terminal BG Setup Tool

window:
  opacity: ${opacity}
  padding:
    x: 10
    y: 10
  decorations: full

# Note: Alacritty doesn't support background images natively
# Use a compositor like picom with feh:
# feh --bg-scale ${imagePath}

# Optional font settings
font:
  size: 11.0`;
        break;

      case 'konsole':
        config = `# Konsole Configuration
# Generated by Terminal BG Setup Tool

Instructions:
1. Open Konsole
2. Settings → Edit Current Profile
3. Appearance tab → Edit color scheme
4. Background tab → Select image
5. Choose: ${imagePath}
6. Set opacity to ${(opacity * 100).toFixed(0)}%
7. Apply and save

# Or manually edit ~/.local/share/konsole/YourProfile.profile:
[Appearance]
ColorScheme=Custom
BackgroundImage=${imagePath}
BackgroundImageOpacity=${opacity}`;
        break;

      case 'terminator':
        config = `# Terminator Configuration (~/.config/terminator/config)
# Generated by Terminal BG Setup Tool

[global_config]
[keybindings]
[profiles]
  [[default]]
    background_image = ${imagePath}
    background_darkness = ${opacity}
    background_type = image
    use_system_font = False
    font = Monospace 11
    scrollback_infinite = True
    
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0

# Restart Terminator after saving`;
        break;

      case 'coolretro':
        if (selectedMethod === 'html') {
          config = `# Cool Retro Term - HTML Animation Setup
# Generated by Terminal BG Setup Tool

1. Save your HTML file to:
   ~/.local/share/cool-retro-term/backgrounds/

2. Launch Cool Retro Term:
   cool-retro-term

3. Right-click → Settings → Background
   - Select your HTML file
   - Adjust opacity: ${(opacity * 100).toFixed(0)}%

4. Enjoy your animated terminal!

# Example HTML file location:
${imagePath}`;
        } else {
          config = `# Cool Retro Term Configuration
# Generated by Terminal BG Setup Tool

1. Copy your ${selectedMethod} to:
   ~/.local/share/cool-retro-term/backgrounds/

2. Launch Cool Retro Term

3. Right-click → Settings → Background
   - Choose: ${imagePath}
   - Opacity: ${(opacity * 100).toFixed(0)}%
   - Enable "Bloom" for glow effect

4. Optional: Enable CRT effects:
   - Screen curvature
   - Scanlines
   - Jitter`;
        }
        break;

      case 'urxvt':
        config = `# URxvt Configuration (~/.Xresources)
# Generated by Terminal BG Setup Tool

URxvt.backgroundPixmap: ${imagePath};100
URxvt.transparent: false
URxvt.shading: ${Math.round(opacity * 100)}
URxvt.depth: 32
URxvt.background: [${Math.round(opacity * 100)}]#000000

# Reload with:
# xrdb ~/.Xresources

# Note: Requires urxvt-pixbuf package:
# sudo pacman -S rxvt-unicode-pixbuf`;
        break;

      default:
        config = 'Please select a terminal emulator';
    }

    setGeneratedConfig(config);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedConfig);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
    }
  };

  const applyPreset = (preset) => {
    setSelectedTerminal(preset.terminal);
    setSelectedMethod(preset.method);
    setOpacity(preset.opacity);
    setActiveTab('config');
  };

  const installCommands = {
    kitty: 'sudo pacman -S kitty',
    alacritty: 'sudo pacman -S alacritty',
    konsole: 'sudo pacman -S konsole',
    terminator: 'sudo pacman -S terminator',
    coolretro: 'yay -S cool-retro-term',
    urxvt: 'sudo pacman -S rxvt-unicode-pixbuf',
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="bg-gradient-to-r from-cyan-500 to-blue-500 rounded-2xl p-8 mb-6 shadow-2xl">
          <div className="flex items-center gap-4 mb-4">
            <Terminal className="w-12 h-12 text-white" />
            <div>
              <h1 className="text-4xl font-bold text-white mb-2">Terminal Background Setup Tool</h1>
              <p className="text-cyan-100">Easy configuration generator for Linux terminal backgrounds</p>
            </div>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="flex gap-2 mb-6 flex-wrap">
          <button
            onClick={() => setActiveTab('select')}
            className={`px-6 py-3 rounded-lg font-bold transition-all ${
              activeTab === 'select'
                ? 'bg-white text-purple-900 shadow-lg'
                : 'bg-purple-800 text-white hover:bg-purple-700'
            }`}
          >
            <Terminal className="inline w-5 h-5 mr-2" />
            Select Terminal
          </button>
          <button
            onClick={() => setActiveTab('method')}
            className={`px-6 py-3 rounded-lg font-bold transition-all ${
              activeTab === 'method'
                ? 'bg-white text-purple-900 shadow-lg'
                : 'bg-purple-800 text-white hover:bg-purple-700'
            }`}
          >
            <Settings className="inline w-5 h-5 mr-2" />
            Choose Method
          </button>
          <button
            onClick={() => setActiveTab('config')}
            className={`px-6 py-3 rounded-lg font-bold transition-all ${
              activeTab === 'config'
                ? 'bg-white text-purple-900 shadow-lg'
                : 'bg-purple-800 text-white hover:bg-purple-700'
            }`}
          >
            <Code className="inline w-5 h-5 mr-2" />
            Generate Config
          </button>
          <button
            onClick={() => setActiveTab('presets')}
            className={`px-6 py-3 rounded-lg font-bold transition-all ${
              activeTab === 'presets'
                ? 'bg-white text-purple-900 shadow-lg'
                : 'bg-purple-800 text-white hover:bg-purple-700'
            }`}
          >
            <Zap className="inline w-5 h-5 mr-2" />
            Presets
          </button>
        </div>

        {/* Tab Content */}
        <div className="bg-white rounded-2xl p-8 shadow-2xl">
          {/* Select Terminal Tab */}
          {activeTab === 'select' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-6">Select Your Terminal Emulator</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {terminals.map((terminal) => (
                  <div
                    key={terminal.id}
                    onClick={() => setSelectedTerminal(terminal.id)}
                    className={`p-6 rounded-xl cursor-pointer transition-all border-2 ${
                      selectedTerminal === terminal.id
                        ? 'border-purple-500 bg-purple-50 shadow-lg scale-105'
                        : 'border-gray-200 hover:border-purple-300 hover:shadow-md'
                    }`}
                  >
                    <div className="flex items-start justify-between mb-3">
                      <h3 className="text-xl font-bold text-gray-800">{terminal.name}</h3>
                      {terminal.popular && (
                        <span className="bg-green-500 text-white text-xs px-2 py-1 rounded-full">Popular</span>
                      )}
                    </div>
                    <div className="space-y-2 text-sm text-gray-600">
                      <div>
                        <strong>Difficulty:</strong> {terminal.difficulty}
                      </div>
                      <div>
                        <strong>Supports:</strong>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {terminal.supports.map((support) => (
                            <span key={support} className="bg-blue-100 text-blue-800 px-2 py-1 rounded text-xs">
                              {support}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                    {selectedTerminal === terminal.id && (
                      <div className="mt-4 pt-4 border-t border-purple-200">
                        <code className="text-xs bg-gray-100 p-2 rounded block">
                          {installCommands[terminal.id]}
                        </code>
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {selectedTerminal && (
                <div className="mt-6 bg-green-50 border-2 border-green-500 rounded-lg p-4">
                  <div className="flex items-center gap-2 text-green-800">
                    <Check className="w-5 h-5" />
                    <span className="font-bold">
                      {terminals.find(t => t.id === selectedTerminal)?.name} selected!
                    </span>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Choose Method Tab */}
          {activeTab === 'method' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-6">Choose Background Method</h2>
              
              {!selectedTerminal && (
                <div className="bg-yellow-50 border-2 border-yellow-500 rounded-lg p-4 mb-6">
                  <div className="flex items-center gap-2 text-yellow-800">
                    <AlertCircle className="w-5 h-5" />
                    <span>Please select a terminal emulator first</span>
                  </div>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                {methods.map((method) => {
                  const Icon = method.icon;
                  const isCompatible = !selectedTerminal || 
                    method.compatible === 'all' || 
                    method.compatible.includes(selectedTerminal);

                  return (
                    <div
                      key={method.id}
                      onClick={() => isCompatible && setSelectedMethod(method.id)}
                      className={`p-6 rounded-xl cursor-pointer transition-all border-2 ${
                        selectedMethod === method.id
                          ? 'border-purple-500 bg-purple-50 shadow-lg'
                          : isCompatible
                          ? 'border-gray-200 hover:border-purple-300 hover:shadow-md'
                          : 'border-gray-200 bg-gray-50 opacity-50 cursor-not-allowed'
                      }`}
                    >
                      <div className="flex items-center gap-3 mb-3">
                        <Icon className="w-8 h-8 text-purple-600" />
                        <h3 className="text-xl font-bold text-gray-800">{method.name}</h3>
                      </div>
                      <p className="text-gray-600 mb-2">{method.desc}</p>
                      <div className="text-xs text-gray-500">
                        Compatible: {method.compatible}
                      </div>
                    </div>
                  );
                })}
              </div>

              {selectedMethod && (
                <div>
                  <h3 className="text-xl font-bold text-gray-800 mb-4">Upload Your File</h3>
                  
                  <label className="block border-2 border-dashed border-purple-300 rounded-xl p-8 text-center cursor-pointer hover:border-purple-500 hover:bg-purple-50 transition-all">
                    <Upload className="w-12 h-12 text-purple-500 mx-auto mb-4" />
                    <div className="text-lg font-semibold text-gray-700 mb-2">
                      {selectedFile ? selectedFile.name : 'Click to upload or drag & drop'}
                    </div>
                    <div className="text-sm text-gray-500">
                      {selectedMethod === 'image' && 'PNG, JPG, or WebP'}
                      {selectedMethod === 'gif' && 'Animated GIF'}
                      {selectedMethod === 'video' && 'MP4 or WebM'}
                      {selectedMethod === 'html' && 'HTML file'}
                    </div>
                    <input
                      type="file"
                      onChange={handleFileSelect}
                      className="hidden"
                      accept={
                        selectedMethod === 'image' ? '.png,.jpg,.jpeg,.webp' :
                        selectedMethod === 'gif' ? '.gif' :
                        selectedMethod === 'video' ? '.mp4,.webm' :
                        '.html'
                      }
                    />
                  </label>

                  <div className="mt-6">
                    <label className="block text-lg font-bold text-gray-800 mb-3">
                      Background Opacity: {(opacity * 100).toFixed(0)}%
                    </label>
                    <input
                      type="range"
                      min="0"
                      max="1"
                      step="0.05"
                      value={opacity}
                      onChange={(e) => setOpacity(parseFloat(e.target.value))}
                      className="w-full h-3 bg-purple-200 rounded-lg appearance-none cursor-pointer"
                    />
                    <div className="flex justify-between text-sm text-gray-600 mt-2">
                      <span>Transparent</span>
                      <span>Opaque</span>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Generate Config Tab */}
          {activeTab === 'config' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-6">Generated Configuration</h2>

              {!selectedTerminal || !selectedMethod ? (
                <div className="bg-yellow-50 border-2 border-yellow-500 rounded-lg p-6">
                  <div className="flex items-center gap-2 text-yellow-800">
                    <AlertCircle className="w-6 h-6" />
                    <span className="font-bold">Please complete steps 1 and 2 first</span>
                  </div>
                </div>
              ) : (
                <div>
                  <button
                    onClick={generateConfig}
                    className="w-full bg-gradient-to-r from-purple-500 to-blue-500 text-white font-bold py-4 px-6 rounded-lg hover:from-purple-600 hover:to-blue-600 transition-all shadow-lg mb-4"
                  >
                    <Zap className="inline w-5 h-5 mr-2" />
                    Generate Configuration
                  </button>

                  {generatedConfig && (
                    <div className="relative">
                      <div className="bg-gray-900 text-green-400 p-6 rounded-lg font-mono text-sm overflow-x-auto">
                        <pre className="whitespace-pre-wrap">{generatedConfig}</pre>
                      </div>
                      <button
                        onClick={copyToClipboard}
                        className="absolute top-4 right-4 bg-purple-500 text-white px-4 py-2 rounded-lg hover:bg-purple-600 transition-all flex items-center gap-2"
                      >
                        {copied ? (
                          <>
                            <Check className="w-4 h-4" />
                            Copied!
                          </>
                        ) : (
                          <>
                            <Copy className="w-4 h-4" />
                            Copy
                          </>
                        )}
                      </button>
                    </div>
                  )}

                  {generatedConfig && (
                    <div className="mt-6 bg-blue-50 border-2 border-blue-500 rounded-lg p-6">
                      <h3 className="font-bold text-blue-900 text-lg mb-3">Next Steps:</h3>
                      <ol className="list-decimal list-inside space-y-2 text-blue-800">
                        <li>Copy the configuration above</li>
                        <li>Open the config file in your preferred editor</li>
                        <li>Paste the configuration</li>
                        <li>Save and restart your terminal</li>
                        <li>Enjoy your new background! 🎉</li>
                      </ol>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Presets Tab */}
          {activeTab === 'presets' && (
            <div>
              <h2 className="text-3xl font-bold text-gray-800 mb-6">Quick Presets</h2>
              <p className="text-gray-600 mb-6">
                Get started quickly with these curated terminal themes. Each preset includes recommended settings for opacity, effects, and compatible terminal emulators.
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {presets.map((preset) => (
                  <div
                    key={preset.id}
                    className={`bg-gradient-to-br ${preset.gradient} rounded-xl p-6 text-white shadow-lg hover:shadow-2xl transition-all cursor-pointer`}
                  >
                    <h3 className="text-2xl font-bold mb-3">{preset.name}</h3>
                    <p className="text-gray-200 mb-4">{preset.description}</p>
                    <div className="bg-black bg-opacity-50 p-4 rounded text-sm mb-4 space-y-1">
                      <div><strong>Opacity:</strong> {(preset.opacity * 100).toFixed(0)}%</div>
                      <div><strong>Effect:</strong> {preset.effect}</div>
                      <div><strong>Color:</strong> {preset.color}</div>
                      <div><strong>Terminal:</strong> {terminals.find(t => t.id === preset.terminal)?.name}</div>
                      <div><strong>Method:</strong> {methods.find(m => m.id === preset.method)?.name}</div>
                    </div>
                    <button
                      onClick={() => applyPreset(preset)}
                      className="w-full bg-white text-gray-900 hover:bg-gray-100 py-3 rounded-lg font-bold transition-all shadow-md"
                    >
                      Apply Preset
                    </button>
                  </div>
                ))}
              </div>

              <div className="mt-8 bg-gradient-to-r from-purple-100 to-blue-100 rounded-xl p-6 border-2 border-purple-300">
                <h3 className="text-xl font-bold text-gray-800 mb-3">💡 Pro Tips</h3>
                <ul className="space-y-2 text-gray-700">
                  <li>• Lower opacity (60-75%) works better for text readability</li>
                  <li>• Higher opacity (85-95%) creates more immersive effects</li>
                  <li>• Use static images for performance-critical workflows</li>
                  <li>• Cool Retro Term offers the most visual customization</li>
                  <li>• Kitty provides the best balance of features and performance</li>
                </ul>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-6 text-center text-white text-sm opacity-75">
          <p>Made with ❤️ for the Linux terminal community</p>
          <p className="mt-2">Support: Kitty • Alacritty • Konsole • Terminator • Cool Retro Term • URxvt</p>
        </div>
      </div>
    </div>
  );
}
